---
title: "Topic"
format: html
editor: visual
---

## 1. Motivation

The motivation of our project is to explore the city data, and explore imputation methods using location information. We want analyze the effect that location in different forms has on the imputation process and in linear model itself.

## 2. Plan

1.  The first step will be to explore NYC Airbnb data and understand variables and types that are in play.
2.  The data set will then need to be cleaned so that imputation and model building can take place.
3.  We will then evaluate the missing value pattern in our data especially with the unit price variable.
4.  A model will then be built to predict the price value of the unit. This model will be ran and summarized.
5.  An imputation model on the price variable will be imputed with values from the model and other that are suspected to be impactful.
6.  The next step will be to transform the latitude and longitude into UTM from degrees.
7.  Then re run imputation methods with new location variables.
8.  Then we will compare methods between the two location forms and analyze the differences.
9.  The write up will include differences between degrees and UTM. Why to use one and why to use the other. What our results showed and how the model was impacted by each method.

## 3. Data Documentation

```{r, warning = F, message = F}
data_documentation <- 
  readr::read_csv(
    "Inside Airbnb Data Dictionary - listings.csv detail v4.3.csv",
    skip = 7, # removed the first 7 rows
    col_names = T) %>% 
  slice(1:(79-4)) # removed the last 4 rows

head(data_documentation)
tail(data_documentation)
```

From the given data documentation ([source](https://docs.google.com/spreadsheets/d/1iWCNJcSutYqpULSQHlNyGInUvHg2BoUGoNRIGa6Szc4/edit?gid=1322284596#gid=1322284596)), it is missing four variables that are present in the listing dataset from Inside Airbnb. 

These four variables are:

-   `availability_eoy`
-   `number_of_reviews_ly`
-   `estimtaed_occupancy_l365d`
-   `estimtaed_revenue_l365d`

## 4. Team Information

Team name: Team Team

Members: Grey Gergen, Tyler Davis, Jesus Rodriguez, Jack Macfadyen
>>>>>>> df18e3e1bc1fc4652db8f2846a365ec50e577b10
